CACHESNUMBER = 15;

DAP_CACHE_LIMITEDSQUADCOUNT=[15,5];
DAP_CACHE_FULLSQUADCOUNT=[25,5];

DAP_CACHE_AREARANGE = 1000;
DAP_CACHE_AREASIZE = 50;

DAP_IED_AREARANGE = 750;

DAP_MARKERSIZE = 200;
DAP_AREASIZE = 100;

DAP_BF_CARGOSEARCHRANGE = 500;
DAP_BF_CARGODROPRANGE = 500;

DAP_BF_TRANSPORT_MINDISTANCE=500;
DAP_BF_TRANSPORT_TIME=180;

DAP_BF_UAVDELAY = 1800;
DAP_BF_UAVHEIGHT = 1000;

DAP_BF_PLAYERSMARKERS=0;
DAP_BF_AI_ENABLED=1;

DAP_BF_AI_UNLIMITEDAMMO=1;
DAP_BF_AI_OVERALLSKILL=1;
DAP_BF_AI_AIMINGSKILL=0.095;
DAP_BF_AI_SPOTSKILL=1;

DAP_BF_CUSTOMLOADOUT=1;

SETWIND [-1,1,true];

DAP_CREWALLOWEDWEAPONS = [""];
DAP_PILOTCLASS = "CAManBase";

if ((isServer) or (isDedicated)) then
{

GLOBALBANLIST = [];
PublicVariable "GLOBALBANLIST";

DAP_ALL_RALLYPOINTS = [];
PublicVariable "DAP_ALL_RALLYPOINTS";

DAP_BF_EAST_TRANSPORT=[];
PublicVariable "DAP_BF_EAST_TRANSPORT";
DAP_BF_WEST_TRANSPORT=[];	
PublicVariable "DAP_BF_WEST_TRANSPORT";

};